import Foundation

struct WordBank {
    // 300+ common words
    static let words: [String] = [
        "the", "be", "to", "of", "and", "a", "in", "that", "have", "it",
        "for", "not", "on", "with", "he", "as", "you", "do", "at", "this",
        "but", "his", "by", "from", "they", "we", "say", "her", "she", "or",
        "an", "will", "my", "one", "all", "would", "there", "their", "what", "so",
        "up", "out", "if", "about", "who", "get", "which", "go", "me", "when",
        "make", "can", "like", "time", "no", "just", "him", "know", "take", "people",
        "into", "year", "your", "good", "some", "could", "them", "see", "other", "than",
        "then", "now", "look", "only", "come", "its", "over", "think", "also", "back",
        "after", "use", "two", "how", "our", "work", "first", "well", "way", "even",
        "new", "want", "because", "any", "these", "give", "day", "most", "us", "great",
        "between", "need", "large", "often", "hand", "high", "place", "hold", "free", "real",
        "life", "few", "north", "open", "seem", "together", "next", "white", "children", "begin",
        "got", "walk", "example", "paper", "group", "always", "music", "those", "both", "mark",
        "book", "letter", "until", "mile", "river", "car", "feet", "care", "second", "enough",
        "plain", "girl", "usual", "young", "ready", "above", "ever", "red", "list", "though",
        "feel", "talk", "bird", "soon", "body", "dog", "family", "direct", "pose", "leave",
        "song", "measure", "door", "product", "black", "short", "number", "class", "wind", "question",
        "happen", "complete", "ship", "area", "half", "rock", "order", "fire", "south", "problem",
        "piece", "told", "knew", "pass", "since", "top", "whole", "king", "space", "heard",
        "best", "hour", "better", "true", "during", "hundred", "five", "remember", "step", "early",
        "keep", "food", "simple", "several", "vowel", "toward", "war", "lay", "against", "pattern",
        "slow", "center", "love", "person", "money", "serve", "appear", "road", "map", "rain",
        "rule", "govern", "pull", "cold", "notice", "voice", "unit", "power", "town", "fine",
        "certain", "fly", "fall", "lead", "cry", "dark", "machine", "note", "wait", "plan",
        "figure", "star", "box", "noun", "field", "rest", "correct", "able", "pound", "done",
        "beauty", "drive", "stood", "contain", "front", "teach", "week", "final", "gave", "green",
        "quick", "develop", "ocean", "warm", "atom", "press", "close", "night", "dry", "lake",
        "program", "east", "ran", "round", "plant", "father", "head", "stand", "own", "page",
        "should", "country", "found", "answer", "school", "grow", "study", "still", "learn", "every",
        "story", "point", "left", "right", "mother", "world", "near", "build", "self", "earth",
        "thought", "island", "cross", "farm", "hard", "start", "might", "city", "tree", "run",
        "sea", "draw", "house", "while", "ago", "hot", "oil", "sit", "deal", "swim"
    ]

    // 500+ sentences of varying length
    static let sentences: [String] = [
        // Short sentences (under 30 chars)
        "the cat sat on the mat",
        "she ran to the store",
        "it was a cold day",
        "he likes to read books",
        "the sun is bright today",
        "we went to the park",
        "they play every day",
        "the dog ran fast",
        "i love this song",
        "she made a cake",
        "it started to rain",
        "he found his keys",
        "we are almost there",
        "the sky is blue",
        "come here right now",
        "he sat by the lake",
        "she spoke too fast",
        "the door was open",
        "i need more time",
        "they left at noon",
        "the bird flew away",
        "she smiled at him",
        "he called his friend",
        "we had a great time",
        "the room was dark",
        "i saw a bright star",
        "he lost his way home",
        "she kept on running",
        "it took a long time",
        "the fire burned low",
        "we watched the sunset",
        "he told a funny joke",
        "the snow fell softly",
        "she drew a picture",
        "he broke the record",
        "they won the game",
        "the road was empty",
        "she read all night",
        "he plays the piano",
        "the wind blew hard",
        "we climbed the hill",
        "she sang a sweet song",
        "the river flows east",
        "he fixed the car",
        "we danced all night",
        "the clock struck noon",
        "she baked some bread",
        "he walked to school",
        "they shared a meal",
        "the train was late",
        // Medium sentences (30-60 chars)
        "practice makes perfect in everything you do",
        "the early bird catches the worm every morning",
        "a journey of a thousand miles begins with one step",
        "knowledge is power and power is responsibility",
        "every cloud has a silver lining behind it",
        "actions speak louder than words ever could",
        "time waits for no one so make it count",
        "the pen is mightier than the sword they say",
        "where there is a will there is always a way",
        "all that glitters is not always pure gold",
        "better late than never but never late is best",
        "curiosity killed the cat but made the human wise",
        "do not count your chickens before they hatch",
        "every dog has its day and today is yours",
        "fortune favors the brave and the prepared mind",
        "good things come to those who wait patiently",
        "honesty is the best policy in all situations",
        "if at first you do not succeed then try again",
        "just believe in yourself and anything is possible",
        "keep your friends close and your enemies closer",
        "laughter is the best medicine for the soul",
        "money cannot buy happiness but it helps a lot",
        "no pain no gain is the rule of hard work",
        "once bitten twice shy is a common reaction",
        "patience is a virtue that few people master",
        "the quick brown fox jumps over the lazy dog",
        "reading is to the mind what exercise is to the body",
        "silence is golden when words cannot express enough",
        "the best things in life are completely free",
        "united we stand but divided we surely fall",
        "variety is the spice of life they always say",
        "what goes around comes around in the end",
        "you cannot teach an old dog new tricks easily",
        "zero in on your goals and never give up on them",
        "the wind howled through the empty streets at night",
        "she walked along the beach watching the waves crash",
        "the old man sat in his chair reading the paper",
        "children laughed and played in the summer rain",
        "the city lights sparkled against the dark sky",
        "he remembered the days when life was much simpler",
        "the garden bloomed with flowers of every color",
        "she poured herself a cup of hot green tea",
        "the stars twinkled in the clear night sky above",
        "they gathered around the fire to share stories",
        "the mountain trail was steep but worth the climb",
        "he opened the window to let the fresh air inside",
        "the coffee shop was warm and full of soft music",
        "she typed quickly without looking at the keyboard",
        "the library was quiet except for turning pages",
        "they built their dream house on top of the hill",
        // Longer sentences (60+ chars)
        "the only way to do great work is to love what you do every single day",
        "in the middle of difficulty lies opportunity waiting to be found",
        "life is what happens when you are busy making other plans for the future",
        "the greatest glory in living lies not in never falling but in rising every time",
        "it does not matter how slowly you go as long as you do not stop moving forward",
        "success is not final and failure is not fatal it is the courage to continue that counts",
        "the future belongs to those who believe in the beauty of their dreams and work hard",
        "you miss every single shot that you do not take so keep trying your very best",
        "the only impossible journey is the one that you never begin to take in your life",
        "believe you can and you are already halfway there on the road to great success",
        "tell me and i forget teach me and i remember involve me and i truly learn",
        "it is during our darkest moments that we must focus to see the light ahead",
        "whoever is happy will make others happy too with their kindness and warmth",
        "life is really simple but we insist on making it far more complicated than it needs to be",
        "the purpose of our lives is to be happy and spread joy wherever we go each day",
        "you only live once but if you do it right once is more than enough for a lifetime",
        "many of the failures in life are people who did not realize how close they were to success",
        "if you look at what you have in life you will always have more than you need to be happy",
        "the mind is everything and what you think is what you will become in the end",
        "strive not to be a success but rather to be of value to others around you",
        "the best time to plant a tree was twenty years ago and the second best time is right now",
        "your time is limited so do not waste it living someone else his life or following their path",
        "the way to get started is to quit talking and begin doing the things that matter most",
        "if life were predictable it would cease to be life and be without any flavor at all",
        "the secret of getting ahead is simply getting started with whatever you have right now today",
        "do not let yesterday take up too much of today or it will steal your tomorrow as well",
        "you learn more from failure than from success so do not let it stop you from trying again",
        "creativity is intelligence having fun and exploring new ideas without fear of judgment at all",
        "when you reach the end of your rope tie a knot in it and hang on with all your might",
        "the real test is not whether you avoid this failure because you will not and that is fine",
        // Common phrases and dialogue
        "how are you doing today",
        "nice to meet you here",
        "what time is the meeting",
        "please send me the report",
        "thank you for your help",
        "i will be there soon",
        "can you help me with this",
        "have a wonderful day ahead",
        "see you later alligator",
        "let me know if you need anything",
        "the weather is nice today outside",
        "i am looking forward to it very much",
        "that sounds like a great idea to me",
        "could you please repeat that for me",
        "i completely agree with you on that point",
        "we should get together sometime soon",
        "it was really nice talking to you today",
        "i hope you have a great weekend ahead",
        "what do you think about this plan we made",
        "i need to finish this before the deadline",
        "do you want to grab some lunch together",
        "i just got back from a long vacation trip",
        "the meeting has been moved to next monday",
        "please let me know your thoughts on this one",
        "i am sorry for the late reply to your message",
        "can we schedule a call for tomorrow morning",
        "i think we are on the right track with this project",
        "the presentation went really well today overall",
        "congratulations on your recent promotion at work",
        "i wanted to follow up on our last conversation",
        // Proverbs and wisdom
        "a penny saved is a penny earned in the long run",
        "do not put all your eggs in one single basket",
        "the grass is always greener on the other side",
        "two wrongs do not make a right in any situation",
        "when the going gets tough the tough get going",
        "you can lead a horse to water but cannot make it drink",
        "a picture is worth more than a thousand spoken words",
        "there is no such thing as a completely free lunch",
        "the squeaky wheel gets the grease first every time",
        "birds of a feather flock together quite naturally",
        "do not bite the hand that feeds you every single day",
        "you cannot make an omelette without breaking some eggs",
        "a watched pot never boils so find something else to do",
        "beggars cannot be choosers when times are very tough",
        "do not cry over spilled milk because it is already gone",
        "every rose has its thorns hidden beneath the petals",
        "the apple does not fall far from the tree at all",
        "people who live in glass houses should not throw stones",
        "rome was not built in a day and neither is greatness",
        "still waters run deep beneath the calm surface",
        // Technology and modern life
        "the internet has changed how we communicate with others",
        "mobile phones have become essential tools in daily life",
        "artificial intelligence is transforming many industries",
        "social media connects people from all around the world",
        "cloud computing allows us to access data from anywhere",
        "electric cars are becoming more popular every single year",
        "online learning has opened doors for many students worldwide",
        "digital photography has replaced film in most situations now",
        "video calls make it easy to stay in touch with distant friends",
        "smart watches can track your health data throughout the day",
        "streaming services have changed how we consume entertainment",
        "remote work has become normal for many office workers now",
        "the global economy depends on fast and reliable communication",
        "renewable energy sources are critical for our future planet",
        "space exploration continues to push the boundaries of science",
        "virtual reality offers new ways to experience the digital world",
        "three dimensional printing is changing manufacturing processes",
        "cybersecurity is important for protecting personal information",
        "automation is reshaping the job market across all industries",
        "blockchain technology could transform financial transactions soon",
        // Nature and science
        "the ocean covers more than seventy percent of the earth surface",
        "trees produce oxygen that we need to breathe every single day",
        "the moon orbits the earth once every twenty seven days roughly",
        "water freezes at zero degrees celsius under normal conditions",
        "the human body contains approximately sixty percent water content",
        "sunlight takes about eight minutes to reach the earth surface",
        "the rainforest is home to millions of different species of life",
        "volcanoes shape the landscape through powerful eruptions over time",
        "the deepest part of the ocean is the mariana trench far below",
        "photosynthesis is the process by which plants make their own food",
        "gravity keeps us grounded on the surface of the earth every day",
        "diamonds are formed under extreme pressure deep within the earth",
        "the speed of light is the fastest speed possible in the universe",
        "coral reefs support an incredible diversity of marine life forms",
        "earthquakes occur when tectonic plates shift beneath the surface",
        "the northern lights are caused by solar particles in the atmosphere",
        "butterflies undergo a complete metamorphosis during their lifetime",
        "the sahara is the largest hot desert in the entire world today",
        "dna carries the genetic instructions for all living organisms",
        "fossils tell us about life that existed millions of years ago",
        // Daily activities
        "i wake up every morning at seven and make myself breakfast",
        "she brushes her teeth twice a day morning and night",
        "he takes the bus to work every single weekday morning",
        "they go grocery shopping on saturday afternoons together",
        "we always eat dinner together as a family at the table",
        "she exercises for thirty minutes every day after work",
        "he reads for an hour before going to sleep at night",
        "they walk the dog around the neighborhood every evening",
        "we clean the house every weekend to keep things tidy",
        "she waters the garden plants every morning before work",
        "he checks his email first thing when he gets to the office",
        "they pick up the children from school at three every day",
        "we cook a special meal every sunday for the whole family",
        "she listens to music while driving to work in the morning",
        "he writes in his journal every night before going to bed",
        "they visit their grandparents once a month on weekends",
        "we watch a movie together every friday night at home",
        "she organizes her desk before starting work each morning",
        "he practices guitar for an hour after dinner every night",
        "they go for a jog in the park every morning at sunrise",
        // Travel and adventure
        "traveling opens your mind to new cultures and experiences",
        "the mountains offer breathtaking views from their peaks",
        "she packed her bags and headed to the airport early morning",
        "the beach was peaceful with waves gently washing the shore",
        "they explored the ancient ruins and learned about history",
        "the train ride through the countryside was truly beautiful",
        "he took photographs of every landmark they visited on the trip",
        "the local food was delicious and unlike anything back home",
        "they sailed across the calm blue waters under a clear sky",
        "the hiking trail led through dense forest to a hidden waterfall",
        "she collected seashells along the sandy shore at sunset",
        "the market was full of colorful crafts and fresh produce",
        "they camped under the stars and told stories around the fire",
        "the museum had artifacts from thousands of years ago on display",
        "he learned a few words in the local language during the trip",
        "the sunset over the valley was the most beautiful sight ever",
        "they rented bicycles and explored the town on two wheels",
        "the hot springs were a perfect way to relax after a long hike",
        "she wrote postcards to her friends and family back home",
        "the adventure of a lifetime began with a single brave step forward",
        // Food and cooking
        "she added a pinch of salt to the boiling water in the pot",
        "the fresh bread from the bakery smelled absolutely wonderful",
        "he grilled the vegetables on the barbecue in the backyard",
        "they made homemade pasta from scratch for the first time",
        "the soup simmered on the stove filling the kitchen with aroma",
        "she sliced the tomatoes and arranged them on the salad plate",
        "he poured the batter into the pan and waited for it to cook",
        "they decorated the cake with fresh berries and whipped cream",
        "the recipe called for two cups of flour and one cup of sugar",
        "she stirred the sauce slowly to prevent it from burning",
        "he squeezed fresh lemon juice over the grilled fish dish",
        "they set the table with plates glasses and folded napkins",
        "the chocolate melted smoothly in the double boiler on the stove",
        "she rolled out the dough thin and cut it into small circles",
        "he seasoned the chicken with herbs and spices before roasting",
        "they enjoyed a three course meal at the new restaurant downtown",
        "the pie crust was golden brown and perfectly flaky all around",
        "she blended the fruits into a smooth and refreshing smoothie",
        "he measured the ingredients carefully following the recipe exactly",
        "they shared a pot of tea and fresh scones on a rainy afternoon",
        // Sports and fitness
        "she ran five miles every morning before the sun came up",
        "he scored the winning goal in the final minute of the game",
        "they practiced together as a team every day after school",
        "the swimmer crossed the finish line in first place overall",
        "she lifted weights three times a week at the local gym",
        "he stretched before and after every workout to stay flexible",
        "they cheered loudly from the stands as their team played well",
        "the basketball bounced off the rim and missed the basket",
        "she completed her first marathon after months of hard training",
        "he taught his daughter how to ride a bicycle in the park",
        "they played tennis on the courts every saturday morning together",
        "the yoga class helped her feel calm and centered after a long day",
        "he swam fifty laps in the pool without stopping for a rest",
        "they trained hard all season and finally won the championship",
        "the coach gave an inspiring speech before the big game started",
        "she set a new personal best in the hundred meter sprint race",
        "he practiced his serve until it was fast and accurate every time",
        "they went rock climbing on the weekend and reached the summit",
        "the referee blew the whistle to signal the end of the match",
        "she jumped higher than anyone else in the high jump competition",
        // Music and arts
        "the piano melody filled the concert hall with beautiful sound",
        "she painted a landscape using bright watercolors on canvas",
        "he strummed the guitar and sang a song he wrote that morning",
        "they performed on stage in front of a large excited audience",
        "the sculpture was carved from a single block of white marble",
        "she danced gracefully across the stage under the spotlight",
        "he composed a piece of music inspired by the sound of rain",
        "they visited the art gallery and admired the modern paintings",
        "the orchestra played a symphony that moved everyone to tears",
        "she wrote poetry about the changing seasons throughout the year",
        "he played the drums with incredible energy and perfect rhythm",
        "they sang together in harmony during the school music festival",
        "the mural on the wall depicted scenes from the town rich history",
        "she took a pottery class and made a beautiful ceramic bowl",
        "he learned to play the violin when he was just seven years old",
        "they organized a community art show to showcase local talent",
        "the jazz band played late into the night at the downtown club",
        "she directed a short film that won an award at the festival",
        "he designed the album cover using digital illustration tools",
        "they collaborated on a song that became a local favorite hit",
        // Emotions and relationships
        "she felt grateful for the kindness of strangers around her",
        "he was proud of his son achievement at the science fair today",
        "they comforted each other during the difficult and trying times",
        "the surprise party made her feel truly loved and appreciated",
        "he apologized sincerely and promised to do much better going forward",
        "they laughed together until tears rolled down their happy faces",
        "she missed her family while studying far away from her home town",
        "he felt a sense of accomplishment after finishing the long project",
        "they held hands and watched the fireworks light up the night sky",
        "the kind words from her teacher gave her confidence to try again",
        "he wrote a heartfelt letter to his best friend from childhood days",
        "they celebrated their anniversary with a quiet dinner for two",
        "she felt inspired after reading the biography of a great leader",
        "he was nervous before the interview but performed really well",
        "they supported each other through every challenge they faced together",
        "the reunion brought tears of joy and countless warm embraces around",
        "she forgave him because holding onto anger only hurts yourself more",
        "he encouraged her to follow her dreams no matter how big they were",
        "they promised to always be honest and kind to one another forever",
        "the friendship they built over the years was stronger than ever now",
        // Work and business
        "the team met every monday morning to discuss weekly goals ahead",
        "she presented her ideas to the board with confidence and clarity",
        "he organized the files and updated the database before lunch time",
        "they launched the new product after months of careful development",
        "the deadline was tight but they managed to deliver on time today",
        "she negotiated a fair deal that benefited both parties equally well",
        "he reviewed the contract carefully before signing on the dotted line",
        "they brainstormed creative solutions to the ongoing problem at hand",
        "the startup grew quickly and attracted many investors from abroad",
        "she mentored the new employees and helped them settle in at work",
        "he balanced multiple projects without missing a single deadline ever",
        "they celebrated the successful quarter with a team outing on friday",
        "the conference brought together experts from around the entire world",
        "she automated several tasks to improve efficiency across the team",
        "he designed a new workflow that saved the company both time and money",
        "they conducted a survey to understand what their customers wanted",
        "the company expanded into three new markets during the past year",
        "she trained her replacement thoroughly before moving to a new role",
        "he wrote a detailed report summarizing the key findings of the study",
        "they worked overtime to ensure the project launched without any issues"
    ]

    static func randomWord() -> String {
        words.randomElement() ?? "type"
    }

    static func wordsForSession(count: Int) -> [String] {
        var result: [String] = []
        var available = words.shuffled()
        while result.count < count {
            if available.isEmpty { available = words.shuffled() }
            result.append(available.removeFirst())
        }
        return result
    }

    static func sentencesForSession(count: Int) -> [String] {
        var result: [String] = []
        var available = sentences.shuffled()
        while result.count < count {
            if available.isEmpty { available = sentences.shuffled() }
            result.append(available.removeFirst())
        }
        return result
    }

    static func mixedForSession(count: Int) -> [String] {
        var result: [String] = []
        for _ in 0..<count {
            if Bool.random() {
                result.append(sentences.randomElement() ?? "practice typing")
            } else {
                result.append(words.randomElement() ?? "type")
            }
        }
        return result
    }
}
